name: Polly Production Deploy

on:
  push:
    branches: [ main ]

jobs:
  synthesize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install boto3
        run: pip install boto3

      - name: Run synthesize.py (Prod)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          python3 synthesize.py
          aws s3 cp output.mp3 s3://$S3_BUCKET/polly-audio/prod.mp3

